/**
 * Get PlayerId.
 *
 * @param client     Client Index.
 * @return        Client PlayerId.
 */
native int Client_GetClientPlayerId(int client);

/**
 * Get Point.
 *
 * @param client     Client Index.
 * @return        Client Point.
 */
native int Client_GetClientPoint(int client);

/**
 * Get Level.
 *
 * @param client     Client Index.
 * @return        Client Level.
 */
native int Client_GetClientLevel(int client);